### ISSUE TITLE
node-data-mapper fails to load under Windows

### ISSUE THREAD

**Issue by tylerjwatson** [benbotto/node-data-mapper-mssql#1]
Hi,

Under win32, insulin fails to bootstrap node-data-mapper-mssql:

```bash
C:\src\bms\server\node_modules\insulin\DependencyInjectionContainer.js:49
      throw new Error(`Factory "${name}" does not exist.`);
            ^
Error: Factory "ndm_C:\src\bms\server\node_modules\node-data-mapper\converter\booleanConverter.js" does not exist.
    at DependencyInjectionContainer.get (C:\src\bms\server\node_modules\insulin\DependencyInjectionContainer.js:49:13)
    at files.forEach.f (C:\src\bms\server\node_modules\node-data-mapper\index.js:17:24)
    at Array.forEach (native)
    at Object.<anonymous> (C:\src\bms\server\node_modules\node-data-mapper\index.js:14:7)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Tyler\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:379:14)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\src\bms\server\node_modules\node-data-mapper-mssql\bootstrap.js:13:1)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Tyler\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:379:14)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\src\bms\server\node_modules\node-data-mapper-mssql\index.js:11:15)
```
Whereas under a POSIX environment it works fine in both js and ts.

**Comment by benbotto** [comment]
Hi @tylerjwatson,

First off, thank you for the bug report.  This was caused by a bad regular expression that was used to pull a filename from an absolute path blindly checking for forward-slashes.  The faulty regular expression was effectively trying to do what `path.basename()` is designed to do, so I fixed this issue by using that method.  Please update to `node-data-mapper-mssql@1.1.3`.

**Comment by tylerjwatson** [comment]
Legend.  Thanks mate 👍
